<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FFMpegCore" Version="5.4.0"/>
        <PackageReference Include="SixLabors.ImageSharp" Version="2.1.13"/>
        <PackageReference Include="System.IO.Hashing" Version="10.0.8"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\OsbMpeg.Parsers\OsbMpeg.Parsers.csproj"/>
    </ItemGroup>

</Project>
